"""Tests for the difficulty calibrator (L3).

The load-bearing tests here are the ones that could plausibly fail:

* ``pass@k`` in log space is checked against exact ``fractions.Fraction``
  arithmetic for every ``(n, c, k)`` with ``n <= 20``, so a sign error or a
  misplaced ``lgamma`` cannot hide behind a plausible-looking float.
* ``StubModel`` is exercised with ``socket`` monkeypatched to raise, which is
  the only way to *prove* the default calibration path is offline rather than
  merely believing it.
* ``fit_2pl`` is asked to recover known ``a`` and ``b`` from data generated by
  the very model it fits. That is the real test: a 2PL fit that does not
  recover its own generative parameters produces a discrimination ranking that
  means nothing.
"""

from __future__ import annotations

import math
import socket
from fractions import Fraction
from pathlib import Path
from typing import Any, Callable

import numpy as np
import pytest

from crucible.calibrate import irt as irt_mod
from crucible.calibrate import models as models_mod
from crucible.calibrate import passk as passk_mod
from crucible.calibrate import router as router_mod
from crucible.calibrate.irt import (
    ContaminationThresholds,
    Priors,
    fit_2pl,
    flag_contamination,
    icc,
    simulate_2pl,
)
from crucible.calibrate.models import (
    STUB_CORRECT_MARKER,
    STUB_INCORRECT_MARKER,
    AnthropicModel,
    LocalModel,
    ModelUnavailable,
    OpenAIModel,
    StubModel,
    TargetModel,
    grade_completion,
    resolve_model,
)
from crucible.calibrate.passk import (
    PassKEstimate,
    estimate,
    jeffreys_interval,
    log_comb,
    pass_at_1,
    pass_at_k,
    wilson_interval,
)
from crucible.calibrate.router import (
    CONSERVATISM_ORDER,
    ROUTES,
    RouteBands,
    calibrate_bank,
    route,
    route_decision,
)


# --------------------------------------------------------------------------- #
# pass@k
# --------------------------------------------------------------------------- #


def _exact_pass_at_k(n: int, c: int, k: int) -> Fraction:
    """Reference implementation in exact rational arithmetic."""
    if k > n:
        raise ValueError("k > n")
    return Fraction(1) - Fraction(math.comb(n - c, k), math.comb(n, k))


@pytest.mark.parametrize(
    "n, c, k, expected",
    [
        (5, 2, 2, 0.7),  # 1 - C(3,2)/C(5,2) = 1 - 3/10
        (6, 2, 3, 0.8),  # 1 - C(4,3)/C(6,3) = 1 - 4/20
        (10, 1, 1, 0.1),
        (10, 1, 10, 1.0),
        (4, 0, 2, 0.0),
        (4, 4, 2, 1.0),
        (8, 3, 8, 1.0),
        (8, 3, 1, 0.375),
        (3, 1, 2, 2.0 / 3.0),  # 1 - C(2,2)/C(3,2) = 1 - 1/3
    ],
)
def test_pass_at_k_matches_hand_computed_values(n: int, c: int, k: int, expected: float) -> None:
    assert pass_at_k(n, c, k) == pytest.approx(expected, abs=1e-12)


def test_pass_at_k_is_not_the_naive_estimator() -> None:
    """The naive (c/n)**k form must not accidentally agree with the real one."""
    n, c, k = 8, 3, 4
    naive = 1.0 - (1.0 - c / n) ** k
    unbiased = pass_at_k(n, c, k)
    assert unbiased != pytest.approx(naive, abs=1e-6)
    # 1 - C(5,4)/C(8,4) = 1 - 5/70
    assert unbiased == pytest.approx(1.0 - 5.0 / 70.0, abs=1e-12)


def test_log_space_agrees_with_exact_fractions_for_small_n() -> None:
    checked = 0
    for n in range(1, 21):
        for c in range(0, n + 1):
            for k in range(1, n + 1):
                got = pass_at_k(n, c, k)
                want = float(_exact_pass_at_k(n, c, k))
                assert got == pytest.approx(want, abs=1e-12), (n, c, k, got, want)
                checked += 1
    assert checked > 1000


def test_log_comb_matches_math_comb() -> None:
    for n in range(0, 30):
        for k in range(0, n + 1):
            assert math.exp(log_comb(n, k)) == pytest.approx(float(math.comb(n, k)), rel=1e-9)
    assert log_comb(5, 6) == -math.inf
    assert log_comb(5, -1) == -math.inf


def test_pass_at_k_monotone_in_c_and_in_k() -> None:
    n = 12
    for k in (1, 3, 7, 12):
        values = [pass_at_k(n, c, k) for c in range(n + 1)]
        assert values == sorted(values)
        assert all(b >= a for a, b in zip(values, values[1:]))
    for c in (0, 1, 5, 11, 12):
        values = [pass_at_k(n, c, k) for k in range(1, n + 1)]
        assert all(b >= a for a, b in zip(values, values[1:]))


def test_pass_at_1_equals_c_over_n() -> None:
    assert pass_at_1(8, 3) == pytest.approx(0.375)
    assert pass_at_1(8, 3) == pytest.approx(pass_at_k(8, 3, 1))


def test_k_greater_than_n_raises_unless_clamped() -> None:
    with pytest.raises(ValueError, match="not estimable"):
        pass_at_k(4, 2, 8)
    assert pass_at_k(4, 2, 8, clamp_k=True) == pytest.approx(pass_at_k(4, 2, 4))


def test_degenerate_inputs_raise() -> None:
    with pytest.raises(ValueError):
        pass_at_k(0, 0, 1)
    with pytest.raises(ValueError):
        pass_at_k(5, 6, 1)
    with pytest.raises(ValueError):
        pass_at_k(5, -1, 1)
    with pytest.raises(ValueError):
        pass_at_k(5, 1, -1)


# --------------------------------------------------------------------------- #
# intervals
# --------------------------------------------------------------------------- #


def test_wilson_interval_known_value_and_containment() -> None:
    lo, hi = wilson_interval(3, 8, 0.95)
    # Hand-computed: z=1.959964, centre=(3+1.9208)/11.8416, half-width as in the source.
    assert lo == pytest.approx(0.1367, abs=5e-4)
    assert hi == pytest.approx(0.6938, abs=5e-4)
    assert lo < 3 / 8 < hi


def test_wilson_interval_is_never_degenerate_at_the_extremes() -> None:
    lo, hi = wilson_interval(0, 8)
    assert lo == pytest.approx(0.0, abs=1e-12)
    assert hi > 0.2, "0/8 must not be reported as a point estimate of exactly zero"
    lo, hi = wilson_interval(8, 8)
    assert hi == pytest.approx(1.0, abs=1e-12)
    assert lo < 0.8


def test_wilson_interval_narrows_with_n() -> None:
    widths = []
    for n in (8, 32, 128, 512):
        lo, hi = wilson_interval(n // 2, n)
        widths.append(hi - lo)
    assert widths == sorted(widths, reverse=True)


def test_jeffreys_interval_brackets_the_point_and_pins_the_endpoints() -> None:
    scipy = pytest.importorskip("scipy.stats")
    assert scipy is not None
    lo, hi = jeffreys_interval(3, 8)
    assert 0.0 < lo < 3 / 8 < hi < 1.0
    assert jeffreys_interval(0, 8)[0] == 0.0
    assert jeffreys_interval(8, 8)[1] == 1.0


def test_estimate_records_the_clamp_note() -> None:
    est = estimate(4, 2, 8)
    assert isinstance(est, PassKEstimate)
    assert est.effective_k == 4
    assert any("exceeds n=4" in note for note in est.notes)
    payload = est.as_dict()
    assert payload["k"] == 8 and payload["effective_k"] == 4
    assert payload["ci_method"] == "wilson"


def test_estimate_ci_contains_point_estimate() -> None:
    est = estimate(8, 3, 8)
    assert est.ci_low <= est.pass_at_1 <= est.ci_high
    assert est.pass_at_k >= est.pass_at_1


def test_estimate_rejects_unknown_ci_method() -> None:
    with pytest.raises(ValueError, match="unknown interval method"):
        estimate(8, 3, 4, ci_method="bootstrap")  # type: ignore[arg-type]


# --------------------------------------------------------------------------- #
# router - every branch
# --------------------------------------------------------------------------- #


def test_route_returns_a_tuple_of_route_and_rationale() -> None:
    got = route(0.375, 0.9, 8)
    assert isinstance(got, tuple) and len(got) == 2
    assert got[0] in ROUTES
    assert got[1].strip()


def test_branch_escalate_when_pass_at_k_is_zero() -> None:
    decision = route_decision(0.0, 0.0, 8)
    assert decision.route == "escalate"
    assert "solvable" in decision.rationale
    assert decision.confident is True


def test_branch_escalate_beats_a_supplied_interval() -> None:
    # Even a wide interval cannot manufacture evidence of solvability.
    decision = route_decision(0.0, 0.0, 8, ci=(0.0, 0.32))
    assert decision.route == "escalate"


def test_branch_reject_when_saturated() -> None:
    decision = route_decision(0.98, 1.0, 8, ci=(0.94, 0.999))
    assert decision.route == "reject"
    assert decision.band == "saturated"
    assert "contamination" in decision.rationale
    assert decision.confident is True


def test_branch_gold_in_band() -> None:
    decision = route_decision(0.375, 0.95, 8, ci=(0.20, 0.60))
    assert decision.route == "gold"
    assert decision.band == "gold"
    assert decision.confident is True
    assert "maximum" in decision.rationale


def test_branch_frontier_when_hard_but_reachable() -> None:
    decision = route_decision(0.02, 0.15, 8, ci=(0.001, 0.08))
    assert decision.route == "frontier"
    assert decision.band == "frontier"
    assert decision.confident is True


def test_branch_thin_band_between_0_7_and_0_9_is_reject_and_says_why() -> None:
    """The band the proposal leaves implicit: resolved explicitly as reject."""
    decision = route_decision(0.80, 0.99, 8, ci=(0.72, 0.88))
    assert decision.route == "reject"
    assert decision.band == "thin"
    assert "implicit" in decision.rationale
    assert "no contamination is implied" in decision.rationale.lower()
    # And it is distinguishable from the saturated case.
    saturated = route_decision(0.98, 1.0, 8, ci=(0.94, 0.999))
    assert saturated.band == "saturated"
    assert decision.rationale != saturated.rationale


def test_boundary_straddle_at_gold_lower_edge_goes_frontier() -> None:
    # 2/8: Wilson 95% is about [0.071, 0.591]; the point estimate is gold but
    # the interval reaches into the frontier band.
    est = estimate(8, 2, 8)
    decision = route_decision(est.pass_at_1, est.pass_at_k, 8, ci=est.ci)
    assert decision.point_route == "gold"
    assert decision.route == "frontier"
    assert decision.confident is False
    assert "straddles" in decision.rationale
    assert "0.10" in decision.rationale


def test_boundary_straddle_at_gold_upper_edge_keeps_the_task() -> None:
    # 4/8: Wilson 95% is about [0.215, 0.785]; a mid-band point estimate must
    # not be discarded because of eight-sample noise.
    est = estimate(8, 4, 8)
    decision = route_decision(est.pass_at_1, est.pass_at_k, 8, ci=est.ci)
    assert decision.point_route == "gold"
    assert decision.endpoint_routes == ("gold", "reject")
    assert decision.route == "gold"
    assert decision.confident is False
    assert "never discards" in decision.rationale


def test_boundary_straddle_from_the_reject_side_is_not_a_discard() -> None:
    # Point estimate in the thin band, interval reaching down into gold.
    decision = route_decision(0.80, 0.99, 8, ci=(0.53, 0.94))
    assert decision.point_route == "reject"
    assert decision.route == "gold"
    assert decision.confident is False


def test_a_very_wide_interval_lands_on_the_most_conservative_route() -> None:
    decision = route_decision(0.50, 0.99, 8, ci=(0.05, 0.95))
    assert set(decision.endpoint_routes) == {"frontier", "reject"}
    assert decision.route == "frontier"
    assert decision.confident is False


def test_no_interval_means_not_confident() -> None:
    decision = route_decision(0.375, 0.95, 8)
    assert decision.route == "gold"
    assert decision.confident is False
    assert "point estimate alone" in decision.rationale


def test_conservatism_order_covers_every_route_exactly_once() -> None:
    assert set(CONSERVATISM_ORDER) == set(ROUTES)
    assert len(CONSERVATISM_ORDER) == len(ROUTES)


def test_router_rejects_inconsistent_and_out_of_range_inputs() -> None:
    with pytest.raises(ValueError, match="non-decreasing"):
        route_decision(0.8, 0.4, 8)
    with pytest.raises(ValueError):
        route_decision(1.5, 1.0, 8)
    with pytest.raises(ValueError):
        route_decision(0.4, 0.9, 0)
    with pytest.raises(ValueError, match="inverted"):
        route_decision(0.4, 0.9, 8, ci=(0.8, 0.2))


def test_custom_bands_shift_the_decision() -> None:
    strict = RouteBands(gold_lo=0.05, gold_hi=0.50, saturated_lo=0.90)
    assert route_decision(0.60, 0.99, 8, ci=(0.55, 0.65), bands=strict).route == "reject"
    assert route_decision(0.60, 0.99, 8, ci=(0.55, 0.65)).route == "gold"


def test_route_bands_validate_their_ordering() -> None:
    with pytest.raises(ValueError):
        RouteBands(gold_lo=0.8, gold_hi=0.2)


# --------------------------------------------------------------------------- #
# models
# --------------------------------------------------------------------------- #


def _forbid_network(monkeypatch: pytest.MonkeyPatch) -> None:
    """Make every socket operation explode, then run the code under test."""

    def _boom(*args: Any, **kwargs: Any) -> Any:
        raise AssertionError("network access attempted during offline calibration")

    monkeypatch.setattr(socket, "socket", _boom)
    monkeypatch.setattr(socket, "create_connection", _boom)
    monkeypatch.setattr(socket, "getaddrinfo", _boom)


def test_stub_model_satisfies_the_protocol() -> None:
    assert isinstance(StubModel(), TargetModel)


def test_stub_model_is_deterministic_across_instances_and_runs(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _forbid_network(monkeypatch)
    a = StubModel(seed=1234).generate("prompt", 8, 0.8, task_id="mut-rowsum-a1b2")
    b = StubModel(seed=1234).generate("prompt", 8, 0.8, task_id="mut-rowsum-a1b2")
    assert a == b
    assert len(a) == 8
    again = StubModel(seed=1234).generate("prompt", 8, 0.8, task_id="mut-rowsum-a1b2")
    assert again == a


def test_stub_model_never_touches_the_network(monkeypatch: pytest.MonkeyPatch) -> None:
    _forbid_network(monkeypatch)
    completions = StubModel().generate("anything", 4, 0.7, task_id="t")
    assert len(completions) == 4
    assert all(
        (STUB_CORRECT_MARKER in c) ^ (STUB_INCORRECT_MARKER in c) for c in completions
    )


def test_stub_pass_probability_varies_by_task_and_seed() -> None:
    stub = StubModel(seed=7)
    probs = {stub.pass_probability(f"task-{i}") for i in range(50)}
    assert len(probs) == 50, "distinct task ids must not collide onto one probability"
    assert min(probs) < 0.3 and max(probs) > 0.7, "the bank must span routing bands"
    assert stub.pass_probability("task-0") != StubModel(seed=8).pass_probability("task-0")


def test_stub_pass_rate_tracks_its_own_probability() -> None:
    stub = StubModel(seed=99)
    for task_id in ("alpha", "beta", "gamma"):
        p = stub.pass_probability(task_id)
        completions = stub.generate("p", 400, 0.8, task_id=task_id)
        observed = sum(1 for c in completions if STUB_CORRECT_MARKER in c) / len(completions)
        assert observed == pytest.approx(p, abs=0.08)


def test_stub_temperature_changes_the_draws_not_the_rate() -> None:
    stub = StubModel(seed=5)
    hot = stub.generate("p", 16, 1.0, task_id="x")
    cold = stub.generate("p", 16, 0.1, task_id="x")
    assert hot != cold
    assert stub.pass_probability("x") == stub.pass_probability("x")


def test_stub_falls_back_to_the_embedded_task_id() -> None:
    prompt = models_mod.embed_task_id("mut-xyz", "fix this")
    assert models_mod.extract_task_id(prompt) == "mut-xyz"
    via_prompt = StubModel().generate(prompt, 6, 0.8)
    direct = StubModel().generate("fix this", 6, 0.8, task_id="mut-xyz")
    assert [STUB_CORRECT_MARKER in c for c in via_prompt] == [
        STUB_CORRECT_MARKER in c for c in direct
    ]


def test_resolve_model_defaults_to_the_offline_stub(monkeypatch: pytest.MonkeyPatch) -> None:
    _forbid_network(monkeypatch)
    for spec in (None, "", "stub", "STUB", "stub:whatever"):
        assert isinstance(resolve_model(spec), StubModel)


def test_resolve_model_constructs_real_adapters_without_calling_them(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _forbid_network(monkeypatch)
    assert isinstance(resolve_model("anthropic:claude-opus-5"), AnthropicModel)
    assert isinstance(resolve_model("claude-opus-5"), AnthropicModel)
    assert isinstance(resolve_model("openai:gpt-4o-mini"), OpenAIModel)
    assert isinstance(resolve_model("gpt-4o-mini"), OpenAIModel)
    assert isinstance(resolve_model("local:qwen"), LocalModel)


def test_resolve_model_rejects_unknown_specs() -> None:
    with pytest.raises(ValueError, match="unknown model spec"):
        resolve_model("mistral-large")


def test_anthropic_model_without_a_key_raises_a_specific_error(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _forbid_network(monkeypatch)
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    model = AnthropicModel()
    with pytest.raises(ModelUnavailable) as excinfo:
        model.generate("hi", 1, 0.8)
    assert "ANTHROPIC_API_KEY" in str(excinfo.value)
    assert "stub" in str(excinfo.value)


def test_openai_model_without_a_key_raises_a_specific_error(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _forbid_network(monkeypatch)
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    with pytest.raises(ModelUnavailable) as excinfo:
        OpenAIModel().generate("hi", 1, 0.8)
    assert "OPENAI_API_KEY" in str(excinfo.value)


def test_local_model_without_a_base_url_raises(monkeypatch: pytest.MonkeyPatch) -> None:
    _forbid_network(monkeypatch)
    monkeypatch.delenv("CRUCIBLE_LOCAL_BASE_URL", raising=False)
    with pytest.raises(ModelUnavailable, match="CRUCIBLE_LOCAL_BASE_URL"):
        LocalModel().generate("hi", 1, 0.8)


def test_anthropic_adapter_drops_temperature_for_models_that_reject_it() -> None:
    assert AnthropicModel(model="claude-opus-5").accepts_temperature() is False
    assert AnthropicModel(model="claude-sonnet-5").accepts_temperature() is False
    assert AnthropicModel(model="claude-haiku-4-5").accepts_temperature() is True


def test_anthropic_refusal_becomes_a_visible_marker_not_an_empty_string() -> None:
    class _Details:
        category = "cyber"

    class _Message:
        stop_reason = "refusal"
        stop_details = _Details()
        content: list[Any] = []

    text = AnthropicModel._text_of(_Message())
    assert models_mod.REFUSAL_MARKER in text
    assert "cyber" in text


def test_grade_completion_uses_the_stub_marker_when_no_verifier_is_given() -> None:
    assert grade_completion(f"x {STUB_CORRECT_MARKER} y").correct is True
    assert grade_completion(f"x {STUB_INCORRECT_MARKER} y").correct is False


def test_grade_completion_refuses_to_guess() -> None:
    with pytest.raises(ValueError, match="refuses to guess"):
        grade_completion("def f(): pass")


def test_grade_completion_accepts_one_and_two_argument_verifiers() -> None:
    one: Callable[[str], bool] = lambda completion: "good" in completion
    seen: list[Any] = []

    def two(completion: str, task: Any) -> bool:
        seen.append(task)
        return "good" in completion

    assert grade_completion("this is good", verify=one).correct is True
    assert grade_completion("this is bad", verify=one).correct is False
    assert grade_completion("this is good", verify=two, task="T").correct is True
    assert seen == ["T"]


def test_grade_completion_lets_a_broken_verifier_fail_loudly() -> None:
    def broken(completion: str) -> bool:
        raise RuntimeError("oracle harness exploded")

    with pytest.raises(RuntimeError, match="exploded"):
        grade_completion("x", verify=broken)


# --------------------------------------------------------------------------- #
# IRT
# --------------------------------------------------------------------------- #


def test_icc_is_a_logistic_curve_through_its_own_difficulty() -> None:
    assert float(icc(1.5, 0.3, 0.3)) == pytest.approx(0.5)
    grid = np.linspace(-4, 4, 50)
    curve = icc(1.2, 0.0, grid)
    assert np.all(np.diff(curve) > 0)
    assert curve[0] < 0.05 and curve[-1] > 0.95


def test_fit_2pl_recovers_known_parameters_from_synthetic_2pl_data() -> None:
    """The real test: generate from known (a, b), fit, assert recovery."""
    rng = np.random.default_rng(20260818)
    n_items, n_resp, trials = 14, 90, 8
    true_a = rng.uniform(0.7, 2.2, size=n_items)
    true_b = rng.uniform(-1.8, 1.8, size=n_items)
    true_theta = rng.normal(0.0, 1.0, size=n_resp)

    successes, n_trials = simulate_2pl(true_a, true_b, true_theta, trials=trials, seed=11)
    fit = fit_2pl(successes, n_trials, priors=Priors())

    assert fit.converged, fit.message
    assert fit.n_items == n_items and fit.n_respondents == n_resp
    assert fit.n_observations == n_items * n_resp

    b_err = np.abs(fit.b - true_b)
    a_err = np.abs(fit.a - true_a)
    assert float(np.corrcoef(fit.b, true_b)[0, 1]) > 0.97, "difficulty ordering not recovered"
    assert float(np.corrcoef(fit.a, true_a)[0, 1]) > 0.85, "discrimination ordering not recovered"
    assert float(np.corrcoef(fit.theta, true_theta)[0, 1]) > 0.95, "ability not recovered"
    assert float(b_err.mean()) < 0.20, f"mean |b - b_hat| = {b_err.mean():.3f}"
    assert float(a_err.mean()) < 0.35, f"mean |a - a_hat| = {a_err.mean():.3f}"

    # Ordering alone is not enough: a 2PL fit can rank items perfectly while
    # reporting the whole scale shrunk or stretched (MAP shrinks theta and the
    # optimiser inflates a to compensate). Pin the scale down too.
    b_slope = float(np.polyfit(true_b, fit.b, 1)[0])
    a_slope = float(np.polyfit(true_a, fit.a, 1)[0])
    assert 0.7 < b_slope < 1.3, f"difficulty scale is off: slope {b_slope:.3f}"
    assert 0.7 < a_slope < 1.3, f"discrimination scale is off: slope {a_slope:.3f}"
    assert float(fit.theta.std()) == pytest.approx(1.0, abs=1e-6)
    assert float(fit.theta.mean()) == pytest.approx(0.0, abs=1e-6)


def test_neg_log_posterior_gradient_matches_finite_differences() -> None:
    """A wrong gradient can still converge somewhere plausible; pin it down."""
    from crucible.calibrate.irt import neg_log_posterior

    rng = np.random.default_rng(3)
    n_items, n_resp = 3, 6
    successes, trials = simulate_2pl(
        [0.8, 1.6, 2.0], [-0.5, 0.0, 1.0], rng.normal(size=n_resp), trials=5, seed=3
    )
    # Make one cell missing so the masking path is exercised too.
    successes[0, 0] = 0.0
    trials[0, 0] = 0.0

    priors = Priors()
    x = rng.normal(scale=0.6, size=2 * n_items + n_resp)
    value, grad = neg_log_posterior(x, successes, trials, n_items, priors)
    assert np.isfinite(value)

    eps = 1e-6
    for i in range(x.size):
        step = np.zeros_like(x)
        step[i] = eps
        up, _ = neg_log_posterior(x + step, successes, trials, n_items, priors)
        down, _ = neg_log_posterior(x - step, successes, trials, n_items, priors)
        numeric = (up - down) / (2 * eps)
        assert numeric == pytest.approx(grad[i], abs=1e-4, rel=1e-4), f"coordinate {i}"


def test_discrimination_ranking_orders_by_separating_power() -> None:
    rng = np.random.default_rng(5)
    true_a = np.array([2.4, 1.5, 0.8, 0.35])
    true_b = np.array([0.0, 0.2, -0.3, 0.1])
    theta = rng.normal(size=140)
    successes, trials = simulate_2pl(true_a, true_b, theta, trials=8, seed=5)
    fit = fit_2pl(successes, trials, item_ids=["sharp", "good", "dull", "flat"])

    ranking = fit.discrimination_ranking()
    assert [s.item_id for s in ranking][0] == "sharp"
    assert [s.item_id for s in ranking][-1] == "flat"
    assert ranking[0].discrimination > ranking[-1].discrimination
    assert ranking[0].peak_information > ranking[-1].peak_information
    assert fit.item("sharp").peak_information == pytest.approx(
        fit.item("sharp").discrimination ** 2 / 4.0
    )


def test_item_response_curve_and_serialisation() -> None:
    successes, trials = simulate_2pl([1.0, 1.4], [0.0, 0.5], np.linspace(-2, 2, 40), trials=4, seed=1)
    fit = fit_2pl(successes, trials, item_ids=["a", "b"], respondent_ids=[f"m{i}" for i in range(40)])
    grid, curve = fit.item_response_curve("a")
    assert grid.shape == curve.shape
    assert np.all(np.diff(curve) > 0)
    payload = fit.as_dict()
    assert payload["n_items"] == 2 and payload["n_respondents"] == 40
    assert [item["item_id"] for item in payload["items"]] == [
        s.item_id for s in fit.discrimination_ranking()
    ]
    assert set(payload["ability"]) == {f"m{i}" for i in range(40)}
    with pytest.raises(KeyError):
        fit.item("nope")


def test_fit_2pl_treats_zero_trial_cells_as_missing_not_as_failures() -> None:
    successes = np.array([[4.0, 0.0], [3.0, 4.0], [4.0, 3.0]])
    trials = np.array([[4.0, 0.0], [4.0, 4.0], [4.0, 4.0]])
    fit = fit_2pl(successes, trials)
    assert fit.n_observations == 5
    assert fit.items()[1].n_trials == 8


def test_fit_2pl_rejects_impossible_input() -> None:
    with pytest.raises(ValueError, match="0 <= successes <= trials"):
        fit_2pl(np.array([[5.0]]), np.array([[4.0]]))
    with pytest.raises(ValueError, match="entirely missing"):
        fit_2pl(np.array([[0.0, 0.0]]), np.array([[0.0, 0.0]]))
    with pytest.raises(ValueError, match="same shape"):
        fit_2pl(np.zeros((2, 3)), np.ones((2, 2)))
    with pytest.raises(ValueError, match="2-D"):
        fit_2pl(np.zeros(3), 1)


def test_priors_validate_their_scales() -> None:
    with pytest.raises(ValueError, match="log_a_sd"):
        Priors(log_a_sd=0.0)


# --------------------------------------------------------------------------- #
# contamination
# --------------------------------------------------------------------------- #


def test_contamination_needs_saturation_and_a_recalled_looking_trace() -> None:
    signal = flag_contamination(
        "mut-a",
        1.0,
        {"mean_tokens": 1800, "backtracks": 0, "entropy": 0.11},
    )
    assert signal.flagged is True
    assert signal.assessed is True
    assert signal.score == pytest.approx(1.0)
    assert len(signal.signals) == 3


def test_contamination_not_flagged_when_pass_rate_is_not_saturated() -> None:
    signal = flag_contamination(
        "mut-b",
        0.5,
        {"mean_tokens": 4000, "backtracks": 0, "entropy": 0.01},
    )
    assert signal.flagged is False
    assert signal.assessed is True
    assert "saturation threshold" in signal.reason


def test_contamination_not_flagged_when_the_trace_looks_exploratory() -> None:
    signal = flag_contamination(
        "mut-c",
        1.0,
        {"mean_tokens": 90, "backtracks": 12, "entropy": 0.92},
    )
    assert signal.flagged is False
    assert signal.assessed is True
    assert signal.signals == ()


def test_contamination_is_unassessed_when_trace_statistics_are_missing() -> None:
    """Absent evidence is reported as absent, never as a clean bill of health."""
    signal = flag_contamination("mut-d", 1.0, {"mean_tokens": 5000})
    assert signal.assessed is False
    assert signal.flagged is False
    assert "UNASSESSED" in signal.reason
    assert set(signal.missing_stats) == {"backtracks", "entropy"}

    none_at_all = flag_contamination("mut-e", 1.0, None)
    assert none_at_all.assessed is False and none_at_all.flagged is False


def test_contamination_accepts_alias_field_names_and_rejects_bad_input() -> None:
    signal = flag_contamination(
        "mut-f", 0.99, {"token_count": 900, "entropy_proxy": 0.2, "mean_backtracks": 0.5}
    )
    assert signal.assessed is True and signal.flagged is True
    with pytest.raises(ValueError):
        flag_contamination("mut-g", 1.4, {})


def test_contamination_thresholds_are_policy_inputs() -> None:
    stats = {"mean_tokens": 700, "backtracks": 0.5, "entropy": 0.5}
    lenient = flag_contamination("mut-h", 1.0, stats)
    strict = flag_contamination(
        "mut-h", 1.0, stats, ContaminationThresholds(min_signals=3, max_entropy=0.6)
    )
    assert lenient.flagged is True
    assert strict.flagged is True
    harsher = flag_contamination("mut-h", 1.0, stats, ContaminationThresholds(min_mean_tokens=5000))
    assert harsher.flagged is False


# --------------------------------------------------------------------------- #
# bank-level driver
# --------------------------------------------------------------------------- #


def _write_bank(tmp_path: Path, make_task: Callable[..., Any], n: int = 6) -> Path:
    bank = tmp_path / "bank"
    bank.mkdir()
    for i in range(n):
        task = make_task(task_id=f"mut-synthetic-{i:03d}", calibration=None)
        task.save(bank / f"{task.task_id}.yaml")
    return bank


def test_calibrate_bank_runs_offline_end_to_end(
    tmp_path: Path, make_task: Callable[..., Any], cfg: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    bank = _write_bank(tmp_path, make_task, n=6)
    _forbid_network(monkeypatch)

    report = calibrate_bank(bank_dir=bank, model="stub", k=8, cfg=cfg)

    assert report.offline is True
    assert report.model == "stub"
    assert len(report.results) == 6
    assert report.errors == ()
    assert sum(report.route_counts.values()) == 6
    for item in report.results:
        assert item.decision.route in ROUTES
        assert item.estimate.n_samples == cfg.calibration_samples
        assert 0 <= item.estimate.n_correct <= item.estimate.n_samples
        assert item.decision.rationale.strip()
        # The driver measures only a whitespace token count; backtracks and
        # entropy cannot be recovered from a finished completion, so a
        # saturated task must come back UNASSESSED rather than clean.
        assert item.contamination.flagged is False
        assert set(item.contamination.missing_stats) == {"backtracks", "entropy"}
        assert item.contamination.assessed is (item.estimate.pass_at_1 < 0.95)


def test_calibrate_bank_is_deterministic(
    tmp_path: Path, make_task: Callable[..., Any], cfg: Any
) -> None:
    bank = _write_bank(tmp_path, make_task, n=4)
    first = calibrate_bank(bank_dir=bank, model="stub", k=8, cfg=cfg)
    second = calibrate_bank(bank_dir=bank, model="stub", k=8, cfg=cfg)
    assert [r.estimate.n_correct for r in first.results] == [
        r.estimate.n_correct for r in second.results
    ]
    assert [r.decision.route for r in first.results] == [r.decision.route for r in second.results]


def test_calibrate_bank_payload_is_json_shaped_for_the_cli(
    tmp_path: Path, make_task: Callable[..., Any], cfg: Any
) -> None:
    import json

    bank = _write_bank(tmp_path, make_task, n=3)
    report = calibrate_bank(bank_dir=bank, model="stub", k=8, cfg=cfg)
    payload = report.as_dict()
    json.dumps(payload)  # must not raise
    assert payload["n_tasks"] == 3
    assert set(payload["route_counts"]) == set(ROUTES)
    assert payload["tasks"][0]["estimate"]["ci_method"] == "wilson"


def test_calibrate_bank_accepts_caller_trace_stats_and_can_flag_contamination(
    tmp_path: Path, make_task: Callable[..., Any], cfg: Any
) -> None:
    bank = _write_bank(tmp_path, make_task, n=4)
    ids = [p.stem for p in sorted(bank.iterdir())]
    supplied = {tid: {"backtracks": 0, "entropy": 0.05, "mean_tokens": 2000} for tid in ids}
    report = calibrate_bank(bank_dir=bank, model="stub", k=8, cfg=cfg, trace_stats=supplied)
    assert all(item.contamination.assessed for item in report.results)
    for item in report.results:
        expected = item.estimate.pass_at_1 >= 0.95
        assert item.contamination.flagged is expected


def test_calibrate_bank_uses_a_supplied_verifier(
    tmp_path: Path, make_task: Callable[..., Any], cfg: Any
) -> None:
    bank = _write_bank(tmp_path, make_task, n=3)
    calls: list[str] = []

    def always_wrong(completion: str, task: Any) -> bool:
        calls.append(getattr(task, "task_id", "?"))
        return False

    report = calibrate_bank(bank_dir=bank, model="stub", k=8, cfg=cfg, verify=always_wrong)
    assert len(calls) == 3 * cfg.calibration_samples
    assert all(item.estimate.n_correct == 0 for item in report.results)
    assert all(item.decision.route == "escalate" for item in report.results)


def test_calibrate_bank_writes_back_only_when_asked(
    tmp_path: Path, make_task: Callable[..., Any], cfg: Any
) -> None:
    from crucible.schema import Task

    bank = _write_bank(tmp_path, make_task, n=2)
    calibrate_bank(bank_dir=bank, model="stub", k=8, cfg=cfg)
    assert all(Task.load(p).calibration is None for p in sorted(bank.iterdir()))

    calibrate_bank(bank_dir=bank, model="stub", k=8, cfg=cfg, write_back=True)
    for p in sorted(bank.iterdir()):
        record = Task.load(p).calibration
        assert record is not None
        assert record.model == "stub"
        assert record.route in ROUTES
        assert record.rationale.strip()


def test_calibrate_bank_reports_unreadable_files_instead_of_aborting(
    tmp_path: Path, make_task: Callable[..., Any], cfg: Any
) -> None:
    bank = _write_bank(tmp_path, make_task, n=2)
    (bank / "broken.yaml").write_text("this: [is not a task", encoding="utf-8")
    report = calibrate_bank(bank_dir=bank, model="stub", k=8, cfg=cfg)
    assert len(report.results) == 2
    assert len(report.errors) == 1
    assert "broken.yaml" in report.errors[0]["path"]


def test_calibrate_bank_rejects_a_missing_directory(tmp_path: Path, cfg: Any) -> None:
    from crucible.errors import CrucibleError

    with pytest.raises(CrucibleError, match="bank directory not found"):
        calibrate_bank(bank_dir=tmp_path / "nope", model="stub", k=8, cfg=cfg)


def test_calibration_record_round_trips_through_the_schema(
    tmp_path: Path, make_task: Callable[..., Any], cfg: Any
) -> None:
    from crucible.schema import Task

    bank = _write_bank(tmp_path, make_task, n=1)
    calibrate_bank(bank_dir=bank, model="stub", k=8, cfg=cfg, write_back=True)
    path = next(iter(sorted(bank.iterdir())))
    reloaded = Task.from_yaml(Task.load(path).to_yaml())
    assert reloaded.calibration is not None
    assert reloaded.calibration.k <= 8


def test_modules_import_cleanly() -> None:
    for module in (passk_mod, router_mod, models_mod, irt_mod):
        assert module.__doc__
        assert module.__all__
