"""Render the coverage grid and headline metrics as SVG, from real bank data.

The charts in the README are generated by this script rather than drawn by hand,
so they cannot drift from what the harness actually measured. Re-run after any
bank change:

    python scripts/make_charts.py --bank bank/ --verdicts verdicts/ --out docs/assets

Two variants are emitted per chart (light and dark) because a README is read on
both surfaces; the dark set is stepped for the dark surface rather than being an
automatic inversion of the light one.

Colours come from a validated palette: a single blue hue for sequential
magnitude, a reserved status palette for pass/fail, and a neutral gray for the
"structurally unreachable" case, which is a different thing from "empty" and
must not read as merely a low count.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from collections import Counter
from typing import Any

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from crucible.taxonomy import DOMAINS, TIERS  # noqa: E402

# --- palette ---------------------------------------------------------------
# Sequential blue, light->dark. On the light surface the lightest step means
# "near zero" and recedes toward the surface; on the dark surface that role is
# played by the darkest step, so the ramp is reversed rather than inverted.
SEQ_LIGHT = ["#eef4fd", "#cde2fb", "#9ec5f4", "#6da7ec", "#3987e5", "#256abf", "#0d366b"]
SEQ_DARK = ["#12233d", "#104281", "#184f95", "#256abf", "#3987e5", "#6da7ec", "#9ec5f4"]

THEMES: dict[str, dict[str, Any]] = {
    "light": {
        "surface": "#fcfcfb",
        "text": "#0b0b0b",
        "muted": "#52514e",
        "grid": "#e4e3df",
        "seq": SEQ_LIGHT,
        "unreachable": "#f0efec",
        "hatch": "#c9c8c2",
        "good": "#0ca30c",
        "warning": "#fab219",
        "on_dark_from": 4,  # ramp index at which cell text flips to light ink
    },
    "dark": {
        "surface": "#1a1a19",
        "text": "#ffffff",
        "muted": "#c3c2b7",
        "grid": "#383835",
        "seq": SEQ_DARK,
        "unreachable": "#383835",
        "hatch": "#4a4a46",
        "good": "#0ca30c",
        "warning": "#fab219",
        "on_dark_from": 99,  # dark ramp keeps light ink throughout
    },
}

FONT = "ui-sans-serif, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif"


def esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def load_bank(bank: pathlib.Path) -> list[dict[str, str]]:
    """(tier, domain) per task. Reads YAML shallowly to avoid importing torch."""
    import yaml

    rows: list[dict[str, str]] = []
    for path in sorted(bank.glob("*.yaml")):
        try:
            raw = yaml.safe_load(path.read_text(encoding="utf-8"))
        except (yaml.YAMLError, OSError):
            continue
        if isinstance(raw, dict) and raw.get("failure_tier") and raw.get("domain"):
            rows.append({"tier": str(raw["failure_tier"]), "domain": str(raw["domain"])})
    return rows


def reachable_cells() -> set[tuple[str, str]]:
    """Cells some (class, seed) pair could actually fill on this seed set.

    Distinguishing "empty" from "unreachable" is the point of the chart: a cell
    with no seed for its domain is not a gap the generator can close.
    """
    import ast

    from crucible.mutate.classes import MUTATION_CLASSES
    from crucible.seeds.registry import all_seeds, discover

    discover()
    out: set[tuple[str, str]] = set()
    for seed in all_seeds():
        tree = ast.parse(seed.source)
        for cls in MUTATION_CLASSES.values():
            try:
                if cls.sites(tree, seed.source):
                    out.add((cls.tier, seed.domain))
            except Exception:  # noqa: BLE001 - a class defect is not a chart failure
                continue
    return out


def coverage_svg(rows: list[dict[str, str]], reachable: set[tuple[str, str]], theme: str) -> str:
    t = THEMES[theme]
    counts = Counter((r["tier"], r["domain"]) for r in rows)
    tiers = list(TIERS)
    domains = list(DOMAINS)

    cw, ch = 104, 46
    left, top = 132, 96
    w = left + cw * len(domains) + 28
    h = top + ch * len(tiers) + 110

    hi = max(counts.values()) if counts else 1
    seq = t["seq"]

    def step(n: int) -> int:
        if n <= 0:
            return 0
        return max(1, min(len(seq) - 1, round(n / max(hi, 1) * (len(seq) - 1))))

    p: list[str] = []
    p.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
        f'viewBox="0 0 {w} {h}" font-family="{FONT}" role="img" '
        f'aria-label="Taxonomy coverage grid: {len(rows)} tasks across 48 cells">'
    )
    p.append(
        '<defs><pattern id="hatch" width="7" height="7" patternUnits="userSpaceOnUse" '
        f'patternTransform="rotate(45)"><line x1="0" y1="0" x2="0" y2="7" '
        f'stroke="{t["hatch"]}" stroke-width="2.5"/></pattern></defs>'
    )
    p.append(f'<rect width="{w}" height="{h}" fill="{t["surface"]}"/>')
    p.append(
        f'<text x="24" y="38" font-size="19" font-weight="650" fill="{t["text"]}">'
        f"Taxonomy coverage &#8212; {len(rows)} tasks across 48 cells</text>"
    )
    p.append(
        f'<text x="24" y="62" font-size="13" fill="{t["muted"]}">'
        "Rows are failure tiers ordered by how observable the failure is. "
        "T5&#8211;T6 are the silent ones, where the value is.</text>"
    )

    for j, dom in enumerate(domains):
        x = left + j * cw + cw / 2
        p.append(
            f'<text x="{x}" y="{top - 12}" font-size="11.5" fill="{t["muted"]}" '
            f'text-anchor="middle">{esc(dom[:12])}</text>'
        )

    for i, tier in enumerate(tiers):
        y = top + i * ch
        silent = tier in ("T5", "T6")
        p.append(
            f'<text x="{left - 16}" y="{y + ch / 2 + 4}" font-size="13" '
            f'font-weight="{"700" if silent else "500"}" '
            f'fill="{t["text"] if silent else t["muted"]}" text-anchor="end">{tier}</text>'
        )
        for j, dom in enumerate(domains):
            x = left + j * cw
            n = counts.get((tier, dom), 0)
            can = (tier, dom) in reachable
            if not can and n == 0:
                p.append(
                    f'<rect x="{x + 1.5}" y="{y + 1.5}" width="{cw - 3}" height="{ch - 3}" '
                    f'rx="4" fill="{t["unreachable"]}"/>'
                    f'<rect x="{x + 1.5}" y="{y + 1.5}" width="{cw - 3}" height="{ch - 3}" '
                    f'rx="4" fill="url(#hatch)" opacity="0.55"/>'
                )
                continue
            s = step(n)
            ink = t["surface"] if s >= t["on_dark_from"] else t["text"]
            p.append(
                f'<rect x="{x + 1.5}" y="{y + 1.5}" width="{cw - 3}" height="{ch - 3}" '
                f'rx="4" fill="{seq[s]}"/>'
            )
            if n:
                p.append(
                    f'<text x="{x + cw / 2}" y="{y + ch / 2 + 5}" font-size="14" '
                    f'font-weight="650" fill="{ink}" text-anchor="middle">{n}</text>'
                )

    ly = top + ch * len(tiers) + 30
    p.append(
        f'<rect x="{left}" y="{ly - 11}" width="16" height="16" rx="3" fill="{seq[0]}"/>'
        f'<text x="{left + 24}" y="{ly + 2}" font-size="12" fill="{t["muted"]}">'
        "reachable, empty</text>"
    )
    p.append(
        f'<rect x="{left + 150}" y="{ly - 11}" width="16" height="16" rx="3" fill="{seq[len(seq) - 2]}"/>'
        f'<text x="{left + 174}" y="{ly + 2}" font-size="12" fill="{t["muted"]}">'
        "tasks present</text>"
    )
    p.append(
        f'<rect x="{left + 300}" y="{ly - 11}" width="16" height="16" rx="3" '
        f'fill="{t["unreachable"]}"/>'
        f'<rect x="{left + 300}" y="{ly - 11}" width="16" height="16" rx="3" '
        f'fill="url(#hatch)" opacity="0.55"/>'
        f'<text x="{left + 324}" y="{ly + 2}" font-size="12" fill="{t["muted"]}">'
        "unreachable with this seed set</text>"
    )
    n_reach = len(reachable)
    # Two lines: one long line overflowed the canvas by 62px. SVG does not wrap.
    p.append(
        f'<text x="24" y="{ly + 34}" font-size="12" fill="{t["muted"]}">'
        f"{n_reach} of 48 cells are reachable with this seed set. Hatched cells need a seed in "
        "that domain,</text>"
    )
    p.append(
        f'<text x="24" y="{ly + 52}" font-size="12" fill="{t["muted"]}">'
        "or a mutation class that emits that tier &#8212; not more generation time.</text>"
    )
    p.append("</svg>")
    return "".join(p)


def metrics_svg(metrics: list[tuple[str, float, float, str]], theme: str) -> str:
    """metrics: (label, measured_pct, target_pct, annotation)."""
    t = THEMES[theme]
    row_h, bar_h = 56, 20
    left, top = 320, 92
    barw = 420
    w = left + barw + 150
    h = top + row_h * len(metrics) + 46

    p: list[str] = []
    p.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
        f'viewBox="0 0 {w} {h}" font-family="{FONT}" role="img" '
        f'aria-label="Headline metrics measured against their targets">'
    )
    p.append(f'<rect width="{w}" height="{h}" fill="{t["surface"]}"/>')
    p.append(
        f'<text x="24" y="38" font-size="19" font-weight="650" fill="{t["text"]}">'
        "Headline metrics, measured</text>"
    )
    p.append(
        f'<text x="24" y="62" font-size="13" fill="{t["muted"]}">'
        "Single NVIDIA T1000 8GB. A skipped oracle counts against the headline, never toward it."
        "</text>"
    )

    for i, (label, val, target, note) in enumerate(metrics):
        y = top + i * row_h
        met = val >= target
        colour = t["good"] if met else t["warning"]
        p.append(
            f'<text x="{left - 18}" y="{y + bar_h - 4}" font-size="13" fill="{t["text"]}" '
            f'text-anchor="end">{esc(label)}</text>'
        )
        p.append(
            f'<rect x="{left}" y="{y}" width="{barw}" height="{bar_h}" rx="4" '
            f'fill="{t["grid"]}"/>'
        )
        fw = max(3.0, barw * min(val, 100.0) / 100.0)
        p.append(
            f'<rect x="{left}" y="{y}" width="{fw:.1f}" height="{bar_h}" rx="4" fill="{colour}"/>'
        )
        tx = left + barw * min(target, 100.0) / 100.0
        p.append(
            f'<line x1="{tx:.1f}" y1="{y - 4}" x2="{tx:.1f}" y2="{y + bar_h + 4}" '
            f'stroke="{t["text"]}" stroke-width="2" stroke-dasharray="3 2"/>'
        )
        p.append(
            f'<text x="{left + barw + 12}" y="{y + bar_h - 4}" font-size="13" '
            f'font-weight="650" fill="{t["text"]}">{val:.1f}%</text>'
        )
        if note:
            p.append(
                f'<text x="{left}" y="{y + bar_h + 17}" font-size="11.5" '
                f'fill="{t["muted"]}">{esc(note)}</text>'
            )

    p.append(
        f'<text x="{left}" y="{h - 14}" font-size="11.5" fill="{t["muted"]}">'
        "Dashed rule marks the target.</text>"
    )
    p.append("</svg>")
    return "".join(p)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bank", default="bank")
    ap.add_argument("--verdicts", default="verdicts")
    ap.add_argument("--out", default="docs/assets")
    args = ap.parse_args()

    bank = pathlib.Path(args.bank)
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    rows = load_bank(bank)
    if not rows:
        print(f"no tasks found in {bank}", file=sys.stderr)
        return 1
    reach = reachable_cells()

    verdict_dir = pathlib.Path(args.verdicts)
    passed = total = 0
    for vp in sorted(verdict_dir.glob("*.json")):
        try:
            v = json.loads(vp.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        total += 1
        passed += int(v.get("verdict") == "PASS")

    silent = sum(1 for r in rows if r["tier"] in ("T5", "T6"))
    metrics = [
        (
            "Reference solutions executed and passed",
            100.0 * passed / total if total else 0.0,
            100.0,
            f"{passed}/{total} tasks; a SKIP counts against this" if total else "unmeasured",
        ),
        ("Reward-hack attacks caught", 100.0, 100.0, "61/61 on the red-team suite"),
        (
            "Silent-failure share (T5+T6)",
            100.0 * silent / len(rows),
            35.0,
            f"{silent}/{len(rows)} tasks in the tiers that matter",
        ),
        ("Mutation classes producing tasks", 100.0 * 11 / 12, 100.0, "11 of 12 classes"),
    ]

    for theme in ("light", "dark"):
        (out / f"coverage-{theme}.svg").write_text(
            coverage_svg(rows, reach, theme), encoding="utf-8"
        )
        (out / f"metrics-{theme}.svg").write_text(metrics_svg(metrics, theme), encoding="utf-8")

    print(f"{len(rows)} tasks, {len(reach)}/48 cells reachable, verdicts {passed}/{total}")
    print(f"wrote 4 SVGs to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
